<?php

   /**
    * Kolja Nolte
    * kolja.nolte@gmail.com
    * http://www.koljanolte.com
    * Created on 2015-10-23 01:10 UTC+7
    */

   /**
    * Class IMDb_Connector_Cache
    */
   class IMDb_Connector_Cache {
      /**
       * Returns the absolute path to IMDb Connector's cache directory.
       *
       * @since 0.2
       *
       * @return string
       *
       */
      public function get_cache_path() {
         $path = str_replace("\\", "/", plugin_dir_path(dirname(__FILE__))) . "cache";

         return (string)$path;
      }

      /**
       * Returns the URL to IMDb Connector's cache directory.
       *
       * @since 0.2
       *
       * @return string
       */
      public function get_cache_url() {
         $cache_url = plugin_dir_url(dirname(__FILE__)) . "cache";

         return (string)$cache_url;
      }

      /**
       * Deletes the cache generated by IMDb Connector.
       *
       * @param string $cache_location
       *
       * @since 0.4
       *
       * @return bool
       */
      public function delete_cache($cache_location = "all") {
         $success = false;
         /** Stop script if cache location has not been defined */
         if(!$cache_location) {
            return false;
         }
         /** Delete local cache */
         if($cache_location === "all" || $cache_location === "local") {
            $cache_path    = $this->get_cache_path();
            $movie_details = glob("$cache_path/*.tmp");
            $posters       = glob("$cache_path/*.jpg");
            $files         = array_merge($movie_details, $posters);
            foreach($files as $file) {
               if(is_writable($file) && unlink($file)) {
                  $success = true;
               }
            }
         }
         /** Delete database cache */
         if($cache_location === "all" || $cache_location === "database") {
            global $wpdb;
            $table = $wpdb->prefix . imdb_connector_get_setting("database_table");
            if($wpdb->query("TRUNCATE $table")) {
               $success = true;
            }
         }

         return (bool)$success;
      }
   }